### ISSUE TITLE
Didn't get how to edit dev.json and dev_no_value.json

### ISSUE THREAD

**Issue by siddharthrawal121** [Param-Raval/editsql-cust#3]
Hi @Param-Raval. I have query regarding the custom database. You said we have to edit the **dev.json** and add our question but do we have to add the query(answer) too?
I will really appreciate if you can help me out

**Comment by Param-Raval** [comment]
Hello @siddharthrawal121 thank you for your question. No, you don't need to add the query answer if you just want to generate query predictions on your questions. You can keep any arbitrary query in place of the query answer.

**Comment by siddharthrawal121** [comment]
Hey @Param-Raval thanks for that. How can we make it more efficient? Lets say when we add new questions in dev.json we have to train it again by run_sparc_editsql.sh. Which takes time to train.

**Comment by Param-Raval** [comment]
It can be made efficient, sure. What I did was just a perfunctory way to reach where I wanted to reach with editsql. I haven't given it much thought but you can surely think of better ways to improve this :)
